DbAtlas
ZaragozaEnJuego/server pull request #12
Opened 2023-04-13 17:51 UTC by Drizzt15

done

2023-04-13 18:14 UTC, arejula27 requested changes
Haz merge de main a tu rama y resuelve lso conflictos primero pls

2023-04-13 18:14 UTC, arejula27 commented on .devcontainer/devcontainer.json
recuerda no subir este

2023-04-17 17:42 UTC, arejula27 commented
Puedes hacer la pr solo con lo que has modificado? se esta cambiendo models/properties y el .zshrc por ejemplo

2023-04-17 17:50 UTC, arejula27 commented
Si lo unico que hace esta pr es añadir la url de atlas cierrala y crea un archivo .env con la config. pasa ese archivo por wasap

2023-04-19 17:29 UTC, p3n4x0 commented
se ha modificado lo del dbAtlas en el pr de middelwareAuth. Cerrar este pr y rama.

2023-04-19 17:29 UTC, closed without merging