middlewareAuth done
ZaragozaEnJuego/server pull request #15
Opened 2023-04-16 14:58 UTC by p3n4x0

2023-04-17 17:48 UTC, arejula27 requested changes
He comentado mucho pero se puede mergear, lo unico que si hay que cambiar antes de pasar a main es la direcciçon. Pon local host, no solo por razones de seguridad sino que si esta el de atlas al hacer cada uno pruebas se puede llenar la bbdd de cosas sin sentido

2023-04-17 17:48 UTC, arejula27 commented on api/controllers/middlewareAuth.ts
> +    const secret = 'cat';
en vez de cat habria que sacalor de config coo el de google

2023-04-17 17:48 UTC, arejula27 commented on api/controllers/middlewareAuth.ts
> +    req.body.user = payload;
por que? si ya esta en el header de la solicitud, si es por facilitar no es mjr poner solo el mail en vez que duplicar un dato?

2023-04-17 17:48 UTC, arejula27 commented on api/models/db.ts
> +var dbURI = "mongodb+srv://774572:1234@cluster0.pszz7mi.mongodb.net/?retryWrites=true&w=majority"
por defecto que este en local, pero si lee de config que ponga el de.env

2023-04-17 17:48 UTC, arejula27 commented on api/routes/auth.ts
>        'cat',
cargar de config

2023-04-19 17:10 UTC, p3n4x0 commented on api/routes/auth.ts
>        'cat',
se deja para mas adelante pq da el mismo erro que en passport

2023-04-19 17:12 UTC, arejula27 commented
conflicts

2023-04-19 17:43 UTC, arejula27 approved these changes

2023-04-19 17:49 UTC, merged