Stats admin
ZaragozaEnJuego/server pull request #48
Opened 2023-05-12 16:39 UTC by ibon-sk

Modelo y servicios documentados en swagger para las estadísticas de administrador realizados

2023-05-12 22:41 UTC, arejula27 requested changes

2023-05-12 22:41 UTC, arejula27 commented on api/controllers/statsAdmin.ts
> + * /properties:
esto creo que esta mal, ya hay un endpoint properties

2023-05-12 22:41 UTC, arejula27 commented on api/controllers/statsAdmin.ts
> +async function collectPropertyPurchaseInfo(req: Request, res: Response) {
si solo haces guardar info de una compra lo que debes hacer es una funcion normal con unico paramtro el kind. Esa funcion será llamada en el controllador de buy y en el de offer, no hay que hacer un endpoint dado que no lo debe llamar el cliente

2023-05-12 22:41 UTC, arejula27 commented on api/models/statsAdmin.ts
> +    date: { type: Date, required: true }
si le metes el default today te ahorras tener que ponerlo luego siemptr

2023-05-13 12:54 UTC, ibon-sk commented on api/models/statsAdmin.ts
> +    date: { type: Date, required: true }
Ahora al crear la instancia en la función de api/controllers asigno a la fecha new Date(). Así solo se requiere como parámetro el id de la propiedad y con eso extraigo también el valor de kind

2023-05-13 16:49 UTC, arejula27 commented on api/controllers/properties.ts
> +    await collectPropertyPurchaseInfo(propertieId)
perfect

2023-05-13 16:51 UTC, arejula27 approved these changes
looks good, si has comprobado que  funciona merge

2023-05-15 00:12 UTC, merged