Users added
ZaragozaEnJuego/server pull request #7
Opened 2023-04-08 16:18 UTC by p3n4x0

2023-04-08 16:22 UTC, arejula27 requested changes

2023-04-08 16:22 UTC, arejula27 commented on .devcontainer/devcontainer.json
Estos cambios hazlos en local pero no los subas

2023-04-08 16:22 UTC, arejula27 commented on api/controllers/users.ts
Esto era lo que tenia que hacer yo hahaha , era solo el schema

2023-04-08 16:22 UTC, arejula27 commented on api/models/users.ts
> +}
mail y rol (admin o usr) lo metemos aqui?

2023-04-08 16:22 UTC, arejula27 commented on api/routes/auth.ts
> +    res.json({ token });
Envia tmb si tiene permisos de admin

2023-04-08 16:27 UTC, arejula27 commented
Falla al compilar, en el log pone que es un import. No se pone la extension al hacer import para que compile antes y despues de usar ts

2023-04-08 16:40 UTC, p3n4x0 commented on api/models/users.ts
> +}
lo añado

2023-04-08 17:00 UTC, arejula27 requested changes

2023-04-08 17:00 UTC, arejula27 commented on api/routes/users.ts
esto que es?

2023-04-11 21:28 UTC, arejula27 approved these changes

2023-04-11 21:28 UTC, merged